//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.25 at 06:08:22 PM TRT 
//


package com.hasansahin.discount;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="newPrice" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="oldPrice" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="appliedDiscount" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="result" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "code",
    "newPrice",
    "oldPrice",
    "appliedDiscount",
    "result",
    "message"
})
@XmlRootElement(name = "DiscountResponse")
public class DiscountResponse {

    @XmlElement(required = true)
    protected String code;
    protected float newPrice;
    protected float oldPrice;
    protected float appliedDiscount;
    protected boolean result;
    @XmlElement(required = true)
    protected String message;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the newPrice property.
     * 
     */
    public float getNewPrice() {
        return newPrice;
    }

    /**
     * Sets the value of the newPrice property.
     * 
     */
    public void setNewPrice(float value) {
        this.newPrice = value;
    }

    /**
     * Gets the value of the oldPrice property.
     * 
     */
    public float getOldPrice() {
        return oldPrice;
    }

    /**
     * Sets the value of the oldPrice property.
     * 
     */
    public void setOldPrice(float value) {
        this.oldPrice = value;
    }

    /**
     * Gets the value of the appliedDiscount property.
     * 
     */
    public float getAppliedDiscount() {
        return appliedDiscount;
    }

    /**
     * Sets the value of the appliedDiscount property.
     * 
     */
    public void setAppliedDiscount(float value) {
        this.appliedDiscount = value;
    }

    /**
     * Gets the value of the result property.
     * 
     */
    public boolean isResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     */
    public void setResult(boolean value) {
        this.result = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

}
