//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.25 at 06:08:22 PM TRT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.hasansahin.com/discount", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.hasansahin.discount;
